server:
  port: 8769

spring:
  aplication:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-ribbon-rest
    api-b:
      path: /api-b/**
      serviceId: eureka-feign
