server:
  port: 8776

spring:
  application:
    name: config-yserverst
  cloud:
    config:
      server:
       git:
        uri: https://github.com/zhangermao123/springcloudlearn2021 #配置文件所在仓库
        default-label: master #配置文件分支
        search-paths: config  #配置文件所在根目录
#    bus:
#      enabled: true #bus启用
#      trace:
#        enabled: true #开启跟踪总线事件
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: zhangwei
#    password: 123456


#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh #必须添加 bus refresh



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/