server:
  port: 8775

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
       git:
        uri: https://github.com/huzhicheng/config-only-a-demo #配置文件所在仓库
        default-label: master #配置文件分支
        search-paths: config  #配置文件所在根目录

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/